// AUTO-GENERATED by scripts/gen-promo-timings.mjs — do not edit by hand.
// Scene durations (seconds) + phrase marks (frames, scene-relative) locked to
// the narration take (76.58s total).
export const FPS = 30;
export const NARRATION_SECONDS = 76.58;
export const SCENES = [
  {
    "k": "hook",
    "s": 10.99,
    "marks": {
      "sub": 131,
      "keeps": 249
    }
  },
  {
    "k": "sweep",
    "s": 11.93,
    "marks": {
      "f0": 97,
      "f1": 140,
      "f2": 180,
      "f3": 221,
      "f4": 269,
      "f5": 310
    }
  },
  {
    "k": "p1",
    "s": 11.02,
    "marks": {
      "chip": 263
    }
  },
  {
    "k": "p2",
    "s": 11.13,
    "marks": {
      "chip": 256
    }
  },
  {
    "k": "p3",
    "s": 9.16,
    "marks": {
      "chip": 173
    }
  },
  {
    "k": "adds",
    "s": 8.96,
    "marks": {
      "chip": 227,
      "show": 169
    }
  },
  {
    "k": "outcome",
    "s": 6.71,
    "marks": {
      "l0": 35,
      "l1": 70,
      "l2": 156
    }
  },
  {
    "k": "cta",
    "s": 6.66,
    "marks": {
      "btn": 116,
      "url": 166
    }
  }
] as const;
export type SceneKey = typeof SCENES[number]['k'];
